/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://dlrxh6bovjfyddhk6q7rbhc2oa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-r2y62ypzxnaolpcqtqtwu72cai",
    "aws_cognito_identity_pool_id": "us-east-1:f35eaae5-6bdf-48c4-a75c-7041b892ef02",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_AsNMpNrJD",
    "aws_user_pools_web_client_id": "143svjihaa87drpt82rvu6pbeb",
    "oauth": {}
};


export default awsmobile;
